version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js version 20 ..."
      - n $NODE_20_VERSION
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'