version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js version 20 ..."
      - n $NODE_20_VERSION
      - cd /codebuild/output/src3139147349/src/github.com/SeanMConnaughton/pipeline-setup
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'